@php $selectedCode = $selected ?? '+91 (IN)'; @endphp
<option value="+1 (US/CA)" {{ $selectedCode == '+1 (US/CA)' ? 'selected' : '' }}>+1 (US/CA)</option>
<option value="+91 (IN)" {{ $selectedCode == '+91 (IN)' ? 'selected' : '' }}>+91 (IN) - India</option>
<option value="+44 (UK)" {{ $selectedCode == '+44 (UK)' ? 'selected' : '' }}>+44 (UK)</option>
<option value="+86 (CN)" {{ $selectedCode == '+86 (CN)' ? 'selected' : '' }}>+86 (CN)</option>
<option value="+81 (JP)" {{ $selectedCode == '+81 (JP)' ? 'selected' : '' }}>+81 (JP)</option>
<option value="+49 (DE)" {{ $selectedCode == '+49 (DE)' ? 'selected' : '' }}>+49 (DE)</option>
<option value="+33 (FR)" {{ $selectedCode == '+33 (FR)' ? 'selected' : '' }}>+33 (FR)</option>
<option value="+39 (IT)" {{ $selectedCode == '+39 (IT)' ? 'selected' : '' }}>+39 (IT)</option>
<option value="+34 (ES)" {{ $selectedCode == '+34 (ES)' ? 'selected' : '' }}>+34 (ES)</option>
<option value="+61 (AU)" {{ $selectedCode == '+61 (AU)' ? 'selected' : '' }}>+61 (AU)</option>
<option value="+7 (RU)" {{ $selectedCode == '+7 (RU)' ? 'selected' : '' }}>+7 (RU)</option>
<option value="+82 (KR)" {{ $selectedCode == '+82 (KR)' ? 'selected' : '' }}>+82 (KR)</option>
<option value="+55 (BR)" {{ $selectedCode == '+55 (BR)' ? 'selected' : '' }}>+55 (BR)</option>
<option value="+52 (MX)" {{ $selectedCode == '+52 (MX)' ? 'selected' : '' }}>+52 (MX)</option>
<option value="+971 (AE)" {{ $selectedCode == '+971 (AE)' ? 'selected' : '' }}>+971 (AE)</option>
<option value="+966 (SA)" {{ $selectedCode == '+966 (SA)' ? 'selected' : '' }}>+966 (SA)</option>
<option value="+65 (SG)" {{ $selectedCode == '+65 (SG)' ? 'selected' : '' }}>+65 (SG)</option>
<option value="+60 (MY)" {{ $selectedCode == '+60 (MY)' ? 'selected' : '' }}>+60 (MY)</option>
<option value="+62 (ID)" {{ $selectedCode == '+62 (ID)' ? 'selected' : '' }}>+62 (ID)</option>
<option value="+66 (TH)" {{ $selectedCode == '+66 (TH)' ? 'selected' : '' }}>+66 (TH)</option>
<option value="+84 (VN)" {{ $selectedCode == '+84 (VN)' ? 'selected' : '' }}>+84 (VN)</option>
<option value="+63 (PH)" {{ $selectedCode == '+63 (PH)' ? 'selected' : '' }}>+63 (PH)</option>
<option value="+27 (ZA)" {{ $selectedCode == '+27 (ZA)' ? 'selected' : '' }}>+27 (ZA)</option>
<option value="+31 (NL)" {{ $selectedCode == '+31 (NL)' ? 'selected' : '' }}>+31 (NL)</option>
<option value="+32 (BE)" {{ $selectedCode == '+32 (BE)' ? 'selected' : '' }}>+32 (BE)</option>
<option value="+41 (CH)" {{ $selectedCode == '+41 (CH)' ? 'selected' : '' }}>+41 (CH)</option>
<option value="+46 (SE)" {{ $selectedCode == '+46 (SE)' ? 'selected' : '' }}>+46 (SE)</option>
<option value="+47 (NO)" {{ $selectedCode == '+47 (NO)' ? 'selected' : '' }}>+47 (NO)</option>
<option value="+45 (DK)" {{ $selectedCode == '+45 (DK)' ? 'selected' : '' }}>+45 (DK)</option>
<option value="+358 (FI)" {{ $selectedCode == '+358 (FI)' ? 'selected' : '' }}>+358 (FI)</option>
<option value="+48 (PL)" {{ $selectedCode == '+48 (PL)' ? 'selected' : '' }}>+48 (PL)</option>
<option value="+90 (TR)" {{ $selectedCode == '+90 (TR)' ? 'selected' : '' }}>+90 (TR)</option>
<option value="+20 (EG)" {{ $selectedCode == '+20 (EG)' ? 'selected' : '' }}>+20 (EG)</option>
<option value="+64 (NZ)" {{ $selectedCode == '+64 (NZ)' ? 'selected' : '' }}>+64 (NZ)</option>
<option value="+351 (PT)" {{ $selectedCode == '+351 (PT)' ? 'selected' : '' }}>+351 (PT)</option>
<option value="+30 (GR)" {{ $selectedCode == '+30 (GR)' ? 'selected' : '' }}>+30 (GR)</option>
<option value="+353 (IE)" {{ $selectedCode == '+353 (IE)' ? 'selected' : '' }}>+353 (IE)</option>
